### ISSUE TITLE
No ConnectionRepository found while running locally

### ISSUE THREAD

**Issue by jbhg** [RawSanj/Spring-Twitter-Stream#2]
While running `mvn spring-boot:run`:

```[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.3.RELEASE:run (default-cli) on project spring-twitter-stream: An exception occurred while running. null: InvocationTargetException: Error creating bean with name 'jsonTweetsController' defined in file [/Users/jbg/Spring-Twitter-Stream/target/classes/com/rawsanj/tweet/controller/JsonTweetsController.class]: Unsatisfied dependency expressed through constructor argument with index 1 of type [org.springframework.social.connect.ConnectionRepository]: No qualifying bean of type [org.springframework.social.connect.ConnectionRepository] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.social.connect.ConnectionRepository] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {} -> [Help 1]```

**Comment by RawSanj** [comment]
You need to update the `/src/main/resources/application.properties` file with Twitter App credentials.
I am updating the Readme file.

**Comment by RawSanj** [comment]
@jbhg I have updated the Readme for Twitter app key config. Hope that helps.
